name: actions

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
        with:
          fetch-depth: 0
      - name: Get version
        id: jjversion
        uses: jjliggett/jjversion-action@ef407dec6f44c10a47e8fbbd9e8aa25ed69f63af
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish application
        run: dotnet publish -c Release -o release
      - name: Change index.html base href from / to CurrentTimeApp for GitHub Pages
        run: sed -i 's/<base href="\/"/<base href="\/CurrentTimeApp\/"/g' release/wwwroot/index.html
      - run: cat release/wwwroot/index.html
      - name: Add .nojekyll as this is not a Jekyll project, to allow files and folders starting with underscores
        run: touch release/wwwroot/.nojekyll
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Upload release.zip
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: release
          path: release/
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a
        if: ${{ github.ref == 'refs/heads/root' }}
        with:
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
