name: actions

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Get version
        id: jjversion
        uses: jjliggett/jjversion-action@d55b6dad24396f19b37a47e88bd5b86a55b1ba17
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish application
        run: dotnet publish --no-restore --no-build -c Release -o release
      - name: Change index.html base href from / to CurrentTimeApp for GitHub Pages
        run: sed -i 's/<base href="\/"/<base href="\/CurrentTimeApp\/"/g' release/wwwroot/index.html
      - run: cat release/wwwroot/index.html
      - name: Add .nojekyll as this is not a Jekyll project, to allow files and folders starting with underscores
        run: touch release/wwwroot/.nojekyll
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Upload release.zip
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: release
          path: release/

  deploy-develop:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: https://jjliggett.github.io/CurrentTimeApp-dev-env/
    if: ${{ github.ref != 'refs/heads/root' }}
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: release
          path: release/
      - name: Change index.html base href from CurrentTimeApp to CurrentTimeApp-dev-env for GitHub Pages
        run: sed -i 's/<base href="\/CurrentTimeApp\/"/<base href="\/CurrentTimeApp-dev-env\/"/g' release/wwwroot/index.html
      - run: ls -R
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          repository-name: jjliggett/CurrentTimeApp-dev-env
          token: "${{ secrets.DEV_PAT_TOKEN }}"
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
          single-commit: true

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: release
          path: release/
      - run: ls -R
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        if: ${{ github.ref == 'refs/heads/root' }}
        with:
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
