name: actions

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/codeql-analysis.yaml'
    branches:
      - root
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/codeql-analysis.yaml'
  workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Get version
        id: jjversion
        uses: jjliggett/jjversion-action@9bf7528b19e4099e2a79d6103ff1673c948d33b0
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --locked-mode CurrentTimeApp/CurrentTimeApp.csproj
      - name: Build
        run: dotnet build -c Release --no-restore CurrentTimeApp/CurrentTimeApp.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal CurrentTimeApp/CurrentTimeApp.csproj
      - name: Publish application
        run: dotnet publish --no-restore --no-build -c Release -o release CurrentTimeApp/CurrentTimeApp.csproj
      - name: Change index.html base href from / to CurrentTimeApp for GitHub Pages
        run: sed -i 's/<base href="\/"/<base href="\/CurrentTimeApp\/"/g' release/wwwroot/index.html
      - run: cat release/wwwroot/index.html
      - name: Add .nojekyll as this is not a Jekyll project, to allow files and folders starting with underscores
        run: touch release/wwwroot/.nojekyll
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Upload release.zip
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: release
          path: release/

  build-android:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Get version
        id: jjversion
        uses: jjliggett/jjversion-action@9bf7528b19e4099e2a79d6103ff1673c948d33b0
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet maui workload
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json
      - name: Install dotnet maui-android workload to build application
        run: dotnet workload restore CurrentTimeApp.MauiBlazor/CurrentTimeApp.MauiBlazor.csproj
      - name: Restore dependencies
        run: dotnet restore --locked-mode CurrentTimeApp.MauiBlazor/CurrentTimeApp.MauiBlazor.csproj
      - name: Build
        run: dotnet build -c Release --no-restore -f net8.0-android CurrentTimeApp.MauiBlazor/CurrentTimeApp.MauiBlazor.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal -f net8.0-android CurrentTimeApp.MauiBlazor/CurrentTimeApp.MauiBlazor.csproj
      - name: Publish application
        run: dotnet publish --no-restore -c Release -o android-release -f net8.0-android CurrentTimeApp.MauiBlazor/CurrentTimeApp.MauiBlazor.csproj
      - run: ls -R
      - name: Upload release.zip
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: android-release
          path: android-release/

  deploy-website-develop:
    runs-on: ubuntu-latest
    needs: build-website
    environment:
      name: development
      url: https://jjliggett.github.io/CurrentTimeApp-dev-env/
    if: ${{ github.ref != 'refs/heads/root' }}
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: release
          path: release/
      - name: Change index.html base href from CurrentTimeApp to CurrentTimeApp-dev-env for GitHub Pages
        run: sed -i 's/<base href="\/CurrentTimeApp\/"/<base href="\/CurrentTimeApp-dev-env\/"/g' release/wwwroot/index.html
      - run: ls -R
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0
        with:
          repository-name: jjliggett/CurrentTimeApp-dev-env
          token: ${{ secrets.DEV_PAT_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
          single-commit: true

  deploy-website-production:
    runs-on: ubuntu-latest
    needs: build-website
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: release
          path: release/
      - run: ls -R
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0
        if: ${{ github.ref == 'refs/heads/root' }}
        with:
          token: ${{ secrets.PROD_PAT_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com

  deploy-release:
    runs-on: ubuntu-latest
    needs:
      - build-android
      - deploy-website-production
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Get version
        id: jjversion
        uses: jjliggett/jjversion-action@9bf7528b19e4099e2a79d6103ff1673c948d33b0
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      - run: git reset --soft HEAD~1
      - name: Get previous version from previous commit
        id: previousversion
        uses: jjliggett/jjversion-action@9bf7528b19e4099e2a79d6103ff1673c948d33b0
      - run: echo "VERSION=$(echo ${{ steps.jjversion.outputs.majorMinorPatch }})" >> $GITHUB_ENV
      - run: echo "PREVIOUS_COMMIT_VERSION=$(echo ${{ steps.previousversion.outputs.majorMinorPatch }})" >> $GITHUB_ENV
      - name: Download build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: android-release
          path: android-release/
      - run: ls -R
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        if: ${{ github.ref == 'refs/heads/root' && env.VERSION != env.PREVIOUS_COMMIT_VERSION }}
        with:
          repo_token: ${{ secrets.PROD_PAT_TOKEN }}
          automatic_release_tag: v${{ env.VERSION }}
          prerelease: false
          files: |
            android-release/com.jjliggett.currenttimeapp.mauiblazor-Signed.apk
            README.md
            LICENSE.md
            